# Generated by Django 3.2.9 on 2021-11-23 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_auto_20211123_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='users',
            field=models.ManyToManyField(related_name='advertisements', through='advertisements.FavoriteAdvertisement', to=settings.AUTH_USER_MODEL),
        ),
    ]
